concurrent = 5
check_interval = 0

[session_server]
  session_timeout = 1800


[[runners]]
  name = "efei@gitlab.com@bettercode"
  url = "https://gitlab.com/"
  token = ""
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

